version: "3"
services:
  upload_server:
    build: ./upload_archive
    image: upload_server
    volumes: 
      - "upload_data:/usr/upload"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - upload
  master:
    image: ./checker_master
    image: checker_master
    volumes:
      - "upload_data:/usr/upload"
      - "worker_data:/usr/checker"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 300M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    networks:
      - upload
      - result
  worker:
    image: ./checker_worker
    image: checker_worker
    volumes:
      - "worker_data:/usr/checker"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.8"
          memory: 300M
      restart_policy:
        condition: on-failure
    networks:
      - result
  mysql:
    image: mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - result
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    expose: 
      - 3306
  result_server:
    image: ./result_server
    image: result_server
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5000"
    networks:
      - result

volumes:
  upload_data:
  worker_data:

networks:
  upload:
  result: